/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './markdown.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../src/components/markdown/markdown.component';
import * as import3 from '../../../../src/services/markdown.service';
const styles_MarkdownComponent:any[] = [import0.styles];
export const RenderType_MarkdownComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_MarkdownComponent,
  data: {}
}
);
export function View_MarkdownComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵqud(402653184,1,{contentView: 0}),
    (l()(),import1.ɵeld(16777216,[
      [
        1,
        3
      ]
      ,
      [
        'contentView',
        1
      ]

    ]
    ,(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)))
  ]
  ,(null as any),(null as any));
}
function View_MarkdownComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'kio-markdown',([] as any[]),(null as any),(null as any),(null as any),View_MarkdownComponent_0,RenderType_MarkdownComponent)),
    import1.ɵdid(770048,(null as any),0,import2.MarkdownComponent,[
      import3.KioNg2MarkdownService,
      import1.ComponentFactoryResolver
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const MarkdownComponentNgFactory:import1.ComponentFactory<import2.MarkdownComponent> = import1.ɵccf('kio-markdown',import2.MarkdownComponent,View_MarkdownComponent_Host_0,{source: 'source'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvTWFjaW50b3NoIEhEIDIvRGV2ZWxvcG1lbnQvUHJvamVjdHMvYWZrbS9raW8vcmVsZWFzZXMva2lvLW5nMi1tYXJrZG93bi9zcmMvY29tcG9uZW50cy9tYXJrZG93bi9tYXJrZG93bi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVm9sdW1lcy9NYWNpbnRvc2ggSEQgMi9EZXZlbG9wbWVudC9Qcm9qZWN0cy9hZmttL2tpby9yZWxlYXNlcy9raW8tbmcyLW1hcmtkb3duL3NyYy9jb21wb25lbnRzL21hcmtkb3duL21hcmtkb3duLmNvbXBvbmVudC50cyIsIm5nOi8vL1ZvbHVtZXMvTWFjaW50b3NoIEhEIDIvRGV2ZWxvcG1lbnQvUHJvamVjdHMvYWZrbS9raW8vcmVsZWFzZXMva2lvLW5nMi1tYXJrZG93bi9zcmMvY29tcG9uZW50cy9tYXJrZG93bi9tYXJrZG93bi5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1ZvbHVtZXMvTWFjaW50b3NoIEhEIDIvRGV2ZWxvcG1lbnQvUHJvamVjdHMvYWZrbS9raW8vcmVsZWFzZXMva2lvLW5nMi1tYXJrZG93bi9zcmMvY29tcG9uZW50cy9tYXJrZG93bi9tYXJrZG93bi5jb21wb25lbnQudHMuTWFya2Rvd25Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2ICNjb250ZW50Vmlldz48L2Rpdj4iLCI8a2lvLW1hcmtkb3duPjwva2lvLW1hcmtkb3duPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7Ozs7OztJQ0FBO2dCQUFBOzs7SUFBQTtLQUFBOzs7SUFBQTs7OyJ9
